name: Push
on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push
        uses: docker/build-push-action@v4
        with:
          username: ianwalter
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ianwalter/playwright
          tags: latest
          tag_with_ref: true
